name: Metrics
on:
  schedule: [{cron: "0 16 * * *"}]
  workflow_dispatch:
  push: {branches: ["main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Metrics Anilist
        uses: lowlighter/metrics@v3.34
        with:
          filename: metrics.plugin.anilist.characters.svg
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta
          plugin_anilist: yes
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: characters
          plugin_anilist_shuffle: yes
          plugin_anilist_user: .user.login

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: UWU-TEAM
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics"

          # Options
          template: classic
          config_display: columns
          base: header, activity, community, repositories, metadata
          commits_authoring: AnGgIt86
          config_timezone: Asia/Jakarta
          plugin_achievements: yes
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          plugin_followup: yes
          plugin_followup_sections: repositories
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          plugin_leetcode: yes
          plugin_leetcode_sections: solved, skills, recent
          plugin_lines: yes
          plugin_people: yes
          plugin_people_limit: 64
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following
          plugin_reactions: yes
          plugin_reactions_display: absolute
          plugin_reactions_ignored: github-actions[bot], dependabot[bot], dependabot-preview[bot]
          plugin_reactions_limit: 200
          plugin_reactions_limit_issues: 100
          plugin_stargazers: yes
          plugin_stars: yes
          plugin_stars_limit: 4
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars
          plugin_traffic: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://lecoq.io
          repositories_forks: yes
