name: Metrics

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 16 * * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: MRT-project
          output_action: commit
          committer_branch: main
          committer_message: "chore: update metrics"

          # Base configuration
          template: classic
          base: header, activity, community, repositories, metadata
          base_hireable: yes
          base_indepth: yes
          base_skip: yes

          # Configuration
          config_octicon: yes
          config_timezone: Asia/Jakarta
          config_twemoji: yes
          config_display: regular

          # Authoring
          commits_authoring: AnGgIt886

          # Anilist plugin
          plugin_anilist: yes
          plugin_anilist_user: Canadaine
          plugin_anilist_medias: anime
          plugin_anilist_sections: characters, watching
          plugin_anilist_limit: 4
          plugin_anilist_limit_characters: 22

          # Achievements plugin (disabled due to error in org)
          plugin_achievements: no

          # Activity plugin
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all

          # Follow-up plugin
          plugin_followup: yes
          plugin_followup_sections: repositories

          # Introduction plugin
          plugin_introduction: yes
          plugin_introduction_title: yes

          # Languages plugin
          plugin_languages: yes
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 16
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%

          # Lines plugin
          plugin_lines: yes

          # People plugin
          plugin_people: yes
          plugin_people_limit: 64
          plugin_people_shuffle: yes
          plugin_people_size: 28
          plugin_people_types: followers, following

          # Stargazers plugin
          plugin_stargazers: yes

          # Topics plugin
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: starred
          plugin_topics_sort: stars

          # Traffic plugin
          plugin_traffic: yes

          # Pagespeed plugin
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          plugin_pagespeed_url: https://t.me/neko_ray_uwu

          # LeetCode plugin (disabled due to org context)
          plugin_leetcode: no

          # Reactions plugin (disabled due to org context)
          plugin_reactions: no

          # Repositories
          repositories_forks: yes
